---
title: "Stock Market Predictions"
author: "Owen Morales"
format:
  html:
    code-fold: true
    code-line-numbers: true
execute:
  error: true
---

```{r message=FALSE, warning=FALSE}

library(tidyverse)
library(ggplot2)
library(dplyr)
library(readr)
library(knitr)

df <- read_rds("https://github.com/byuistats/data/raw/refs/heads/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.RDS")
view(df)

```

### Cleanup

The contestant_period column is not “tidy” we want to create a month_end and a year_end column from the information it contains.

```{r}

# https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/regex

tidyDf <- df %>%
  mutate(
    monthEnd = str_extract(contest_period, "(?<=-)[A-Za-z]+"),
    yearEnd = str_extract(contest_period, "\\d{4}$")
  )

head(tidyDf)

```

```{r}

write_rds(tidyDf, "tidy_data.rds")

testRead <- read_rds("tidy_data.rds")
testRead

```

```{r}

# https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html

djiaTable <- tidyDf %>%
  filter(variable == "DJIA") %>%
  select(monthEnd, yearEnd, value) %>%
  rename(Month = monthEnd) %>%
  # I was having a NA issue on December, it seems there was some typos on the original dataset so I am just cleaning them here.
  # Using some ^ and * to say "if it starts with Feb or Dec, replace it with the full month name"
  mutate(Month = str_replace(Month, "^Feb.*", "February")) %>%
  mutate(Month = str_replace(Month, "^Dec.*", "December")) %>%
  mutate(Month = factor(Month, levels = month.name)) %>%
  mutate(value = as.character(value)) %>%
  pivot_wider(names_from = yearEnd, values_from = value, values_fill = "-") %>%
  arrange(Month)

kable(djiaTable)

```